### ISSUE TITLE
List type がNotionで指定したのと違う

### ISSUE THREAD

**Issue by nuovotaka** [otoyo/astro-notion-blog#126]
## 不具合の概要

Notionでアラビア数字のリストを作成したがデプロイ後のリストはアルファベット（小文字）となっていた。
行頭で作成していてネストしているわけではない。

## 再現方法

1. Notionにて番号付きリストを作成する。
2. デプロイを行いブログを見る。
3. ネストされていないのにアルファベット（小文字）が表示。

デプロイまでできており公開された URL で不具合が確認できる場合には URL も記載します。

blog.nuovotaka.com

## 期待する挙動

ネストしない場合は、番号付きリストを表示してほしいです。

## スクリーンショット
- **Notion 側の記述**
<img width="619" alt="スクリーンショット 2023-04-20 17 15 04" src="https://user-images.githubusercontent.com/11598404/233303825-3b3c5dbb-e055-4dee-b56d-2058aab0d309.png">

- **デプロイ後のブログの表示**
<img width="661" alt="スクリーンショット 2023-04-20 17 15 26" src="https://user-images.githubusercontent.com/11598404/233304018-b741560c-dd77-45a1-840c-1925bf44941a.png">

## リポジトリとブランチ名

astro-notion-blog-2023 / main

## デスクトップ環境

- OS: [MacOS Big Sur 11.7.6]
- ブラウザ: [Brave]
- ブラウザのバージョン: [1.50.121]

**Comment by otoyo** [comment]
@nuovotaka 
ご報告ありがとうございます。こちら再現を確認しましたので下記で修正しました。
ご確認いただき、解決していましたらクローズお願いいたします。
https://github.com/otoyo/astro-notion-blog/pull/127
