### ISSUE TITLE
Exif削除によって記事の画像の向きが変わる

### ISSUE THREAD

**Issue by Suzu-Gears** [otoyo/astro-notion-blog#151]
## 不具合の概要
Exif削除によって回転情報が無くなった画像の向きが変わり、Notion上とは異なる表示になってしまうことに気づきました。
![image](https://github.com/otoyo/astro-notion-blog/assets/47468734/085ec7bd-84c2-45f6-82d2-7fa69d9c1500)

## 再現方法
Exifに回転情報がある画像を使った記事をビルドする。

## 期待する挙動
Exifは
・位置情報(+撮影者情報)のみを削除
・回転情報のみを保持して他を削除
のどちらかが良いと考えられます。
専らスマートフォンで撮影した写真を使っているため位置情報にしか気づきませんでしたが、Exifの中には撮影者情報なども含まれることを知ったので、後者のホワイトリスト方式がシンプルで楽そうです。

**Comment by otoyo** [comment]
ご報告ありがとうございます。
Exif削除の対応を行ったときに Orientation も消されてしまうのではないかとは少し思っていたので、検証いただいて助かりました。
こちらすぐ対応できるので対応しますね。

**Comment by otoyo** [comment]
@Suzu-Gears こちらで対応しましたのでご確認ください。
https://github.com/otoyo/astro-notion-blog/pull/152

**Comment by Suzu-Gears** [comment]
確認できました！
![image](https://github.com/otoyo/astro-notion-blog/assets/47468734/98b8fff8-ef10-475b-af1c-7625081f4aee)
ご対応ありがとうございました。
