### ISSUE TITLE
コールアウトの絵文字(アイコン)を削除するとエラーが発生する

### ISSUE THREAD

**Issue by Suzu-Gears** [otoyo/astro-notion-blog#155]
## 不具合の概要
コールアウトの絵文字(アイコン)を削除する方法を偶然発見し、削除したままビルドしたところエラーが発生した。

## 再現方法
![コールアウト アイコン削除](https://github.com/otoyo/astro-notion-blog/assets/47468734/ce752243-e897-4f9d-b127-d448d1206790)
コールアウト内のアイコンではなく、左の6つの点からアイコンのメニューを開くと削除の項目がありました。
これはデスクトップ版ですが、ブラウザ版でも同様の挙動です。

## エラーログ
<img width="916" alt="image" src="https://github.com/otoyo/astro-notion-blog/assets/47468734/5751026c-09ca-4f87-8295-231dffb860ea">

## 期待する挙動
<img width="224" alt="image" src="https://github.com/otoyo/astro-notion-blog/assets/47468734/ad429744-77d3-4e5d-b682-0335bef79514">

絵文字が空であるときには、デフォルトでページメンションのアイコンと似たものが表示されているようです。
しかし、わざわざNotionで絵文字を空にするので、astro-notion-blog上では絵文字とアイコンのスペースが無い、ただの色付きテキストボックスみたいなものになったら良いなと思います。

![image](https://github.com/otoyo/astro-notion-blog/assets/47468734/14719de2-3f05-4c0f-886c-d6e0f90471bb)
イメージ

**Comment by otoyo** [comment]
アイコンを削除できるの知りませんでした。教えていただきありがとうございます。こちら対応しますね。

**Comment by otoyo** [comment]
https://github.com/otoyo/astro-notion-blog/pull/156 で対応しました。

**Comment by Suzu-Gears** [comment]
コールアウトの活用幅が増えて嬉しいです。
ご対応ありがとうございました！！
