### ISSUE TITLE
小さい画像の下に長いキャプションを書くと、画像が左に寄っていく

### ISSUE THREAD

**Issue by Suzu-Gears** [otoyo/astro-notion-blog#174]
## 不具合の概要
メインカラムの横幅よりも小さい画像の下に画像の横幅よりも長いキャプションを書くと、キャプションが画像の横幅をはみ出してfigure要素の横幅となってしまい、画像がどんどん左に寄ってしまう。

![image](https://github.com/otoyo/astro-notion-blog/assets/47468734/bc713ba0-4dbd-4d61-b0ed-8d76a1906724)

## 期待する挙動
↓のようにキャプションの長さに関わらず画像が中央寄せを維持するか、

![image](https://github.com/otoyo/astro-notion-blog/assets/47468734/a1a22445-af7a-461d-a636-eb31bca085cb)

↓のNotionのように画像の横幅を超えるキャプションは自動で折り返されるのが良いと思います。

![image](https://github.com/otoyo/astro-notion-blog/assets/47468734/07447be4-5f93-4d5d-abd1-f81eab78bb03)

しかし、どちらが良いのかというのは判断が付きませんでした。
この点はお任せしたいです。よろしくお願いします。

**Comment by otoyo** [comment]
Captionコンポーネントの `div` の内側にもう一つ `div` を定義して下記のようにスタイルを設定するとできそうです。
https://stackoverflow.com/questions/9769587/set-div-to-have-its-siblings-width

**Comment by Suzu-Gears** [comment]
この方法で上手くいきました！
PR作ります。
