### ISSUE TITLE
アップロードした画像に表示されないものがある

### ISSUE THREAD

**Issue by mosugi** [otoyo/astro-notion-blog#180]
## 不具合の概要

Notionにアップロードした画像のうち一部の画像ががblog上では表示されない。

## 再現方法

1. [クイックスタート](https://github.com/otoyo/astro-notion-blog/blob/main/README.ja.md#motor_scooter-%E3%82%AF%E3%82%A4%E3%83%83%E3%82%AF%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88) の手順を 7 まで実施する
2. [カスタマイズするには](https://github.com/otoyo/astro-notion-blog/blob/main/README.ja.md#hammer_and_pick-%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA%E3%81%99%E3%82%8B%E3%81%AB%E3%81%AF) の手順を実施する
3. ローカルにCloneしたリポジトリで `npm run dev` を実行する（`npm run build` した場合も同様）

下記のページでも同様に発生しているようです。

https://astro-notion-blog-otoyo.vercel.app/posts/a-trip-to-miyakojima-island

## エラーログ

エラーログは出力されていませんが、画像が0バイトで壊れてダウンロードされているように見えます。

```
~/g/g/o/astro-notion-blog ❯❯❯ cd dist/notion/ed4d6f2f-c710-4861-b540-5c4ed44e8729
~/g/g/o/a/d/n/ed4d6f2f-c710-4861-b540-5c4ed44e8729 ❯❯❯ ll
total 0
-rw-r--r--  1 xxx  staff     0B Dec  1 10:36 EC946DBE-9A4C-47BA-827D-C0181EB54B0E.jpeg
```

## 期待する挙動

画像が表示される。

## スクリーンショット

![image](https://github.com/otoyo/astro-notion-blog/assets/4524414/09908eb1-2f11-4b1a-841a-073fda8b7854)

## デスクトップ環境

- OS: MacOS
- ブラウザ: Chrome
- ブラウザのバージョン: 119.0.6045.159（Official Build） （arm64）

## スマートフォン環境:

- デバイス: [例 iPhone6]
- OS: [例 iOS8.1]
- ブラウザ: [例 Chrome, Safari]
- ブラウザのバージョン [例 22]

## 追加情報

自分が新しくアップロードした画像は表示されたので、コピーした画像・古い画像の場合に発生しているように思われます。

Astro * Notionの組み合わせがイケていて素晴らしく、ぜひ自分のサイトでも利用したいと思っておりますので、お手数ですがご確認をお願いします。

**Comment by otoyo** [comment]
不具合のレポートありがとうございます。私の方でも確認できましたので対応します。
対応までしばらくお待ちください。

**Comment by otoyo** [comment]
ローカルでの `npm run dev` 実行時に再現。
レスポンスヘッダの `Content-Length` が0になってしまっている。
![image](https://github.com/otoyo/astro-notion-blog/assets/1063435/73bde90f-9d0c-43b4-8394-279800cd2659)

画像URLに直接アクセスすると問題なく画像は表示される。

**Comment by otoyo** [comment]
↑の問題は https://github.com/otoyo/astro-notion-blog/pull/181 で修正したが、本件とは別問題の模様。プレビュー環境で再現を確認。

**Comment by otoyo** [comment]
プレビュー環境
https://d0eb98f4.astro-notion-blog.pages.dev/posts/a-trip-to-miyakojima-island/
![image](https://github.com/otoyo/astro-notion-blog/assets/1063435/61c13202-8ac5-4a90-8d5b-c1fefda6f38a)

**Comment by otoyo** [comment]
試しに新しく画像を追加したところ、同じように画像が表示されなかった。
![image](https://github.com/otoyo/astro-notion-blog/assets/1063435/ee74e286-5bad-4bd0-b397-f5bb6bfbdccd)

**Comment by otoyo** [comment]
@mosugi https://github.com/otoyo/astro-notion-blog/pull/183 で修正しましたのでご確認ください。

**Comment by mosugi** [comment]
@otoyo ありがとうございます！こちらの環境でも確認できました

**Comment by otoyo** [comment]
@mosugi ご確認ありがとうございました。
