### ISSUE TITLE
I got a update error afer I modified a file.

### ISSUE THREAD

**Issue by lynnww** [otoyo/astro-notion-blog#192]
## Describe the bug

I add a Comments.astro file in component directory, and I modified the [slug].astro. When I commit the files , github give me some error like this:
![image](https://github.com/otoyo/astro-notion-blog/assets/7655742/9f8822c3-acef-478f-a077-01ab7e09b7bd)
![image](https://github.com/otoyo/astro-notion-blog/assets/7655742/53bcb4a9-8995-4dfc-bfbd-8535f6182a36)
So I updated the lint.yml like this
`    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          node-version: 16`
Then I recommit the files and it continue to report error:
![image](https://github.com/otoyo/astro-notion-blog/assets/7655742/93a39952-8472-493d-bc2d-0619e71c1e6f)

## To Reproduce

1. Go to 'src/pages/post/[slug].astro'
2. Click on 'edit this file' and make some change on it.
3. Commit and it report error
![image](https://github.com/otoyo/astro-notion-blog/assets/7655742/c8129e8c-b275-4662-a992-56c99fc08a80)

**Comment by otoyo** [comment]
Run `npm run lint` in your local so that you can see where those errors came from.
If it passes, run `npm run format` to format your code automatically.

**Comment by otoyo** [comment]
FYI: I have updated the Node version and the runner versions of GitHub Actions so the warnings should disappear.
https://github.com/otoyo/astro-notion-blog/pull/193
