### ISSUE TITLE
wiki に記載の方法で、うまく favicon が設定できない。

### ISSUE THREAD

**Issue by okash1n** [otoyo/astro-notion-blog#199]
## 不具合の概要

[Wiki](https://github.com/otoyo/astro-notion-blog/wiki/favicon-%E3%81%AE%E8%A8%AD%E5%AE%9A%E6%96%B9%E6%B3%95) に記載の方法では相対パスになっているので、トップページでしか favicon が表示されません。

## 再現方法

不具合を再現する方法を下記の例のように箇条書きで記述します。

1. [Wiki](https://github.com/otoyo/astro-notion-blog/wiki/favicon-%E3%81%AE%E8%A8%AD%E5%AE%9A%E6%96%B9%E6%B3%95) に記載の通り、 `/public/favicon.svg` を配置し、 `/layout/Layout.astro` の `<head>` 内に `<link rel="icon" href="favicon.png">` を追記

## 追加情報

以下のように変更すると全部のページで表示されました

`<link rel="icon" href={getStaticFilePath('/favicon.svg')} />`

**Comment by otoyo** [comment]
ありがとうございます。おっしゃる通りです。Wikiを修正しました。
