### ISSUE TITLE
Notion上でURLを貼り付ける際に「Mention」を選択した場合、blog上で表示されない

### ISSUE THREAD

**Issue by ykkd** [otoyo/astro-notion-blog#209]
## 不具合の概要
- 表題の通りです。
  - [こちら](https://astro-notion-blog-2.pages.dev/posts/introduction-of-astro-notion-blog/)のページで検証しております。 
    - Pasting url with option “Mention”の下の部分が空欄になっておりますが、これはNotion上ではURLを貼っています 

## 期待する挙動
- URLが表示されて欲しいです

**Comment by otoyo** [comment]
@ykkd メンションしているリンク先のページは同じデータベース内のページでしょうか？
もしデータベース外のページであれば想定通りの挙動となります。

**Comment by ykkd** [comment]
@otoyo 
メンション先は外部URL( https://www.google.com/ )です。

想定通りの挙動とのこと、承知いたしました。
ご教示いただきありがとうございます。
