### ISSUE TITLE
ビルド高速化機能の検証に参加する方法

### ISSUE THREAD

**Issue by otoyo** [otoyo/astro-notion-blog#25]
ビルド高速化機能の検証にご参加いただきありがとうございます。
この機能は astro-notin-blog にとって重要で複雑な機能であるため、リリース前に検証したいと思っています。
検証にご協力いただける方は、後述の手順を実行し最後に下記をご報告ください。

## 期間

2023/2/3(金)まで（予定）

## 報告いただく内容

1. ビルドの成否
    * エラーの場合はエラーメッセージの内容
    * デバッグに協力いただけるか否か
2. ビルドしたブログの記事数とビルドにかかった時間
3. 手順でわかりにくかったところ

## 機能の概要

* ブロックを取得するNotion APIレスポンスのキャッシュ(Nx Cloudを使用)
* 画像、ブックマークページの並列取得
* 外部URL取得時のタイムアウト追加

## 検証手順

ローカルの開発環境はすでにあるものとします。
ブランチ `feature-speedup-build` https://github.com/otoyo/astro-notion-blog/pull/21 をローカルにチェックアウトします。

1. 下記コマンドを実行し Nx Cloud のアクセストークンを生成します

```bash
yarn install && yarn nx g @nrwl/nx-cloud:init
```

2. プロジェクトルートにある `nx.json` を開き `accessToken` の値をメモします
3. 下記コマンドを実行して `nx.json` から `accessToken` を削除します

```sh
git checkout -- nx.json
```

4. ブラウザで [Nx Cloud](https://nx.app/) を開いてアカウントを作成しサインインします
5. "Connect a Workspace" を選択します

<img src="https://user-images.githubusercontent.com/1063435/215296989-296836ae-42f1-42d4-b238-696cbd261722.png" width="600">

6. "01 Check for Nx Cloud package" で "Yes, I'm using @nrwl/nx-cloud" を選択します

<img src="https://user-images.githubusercontent.com/1063435/215296991-313ebd38-252a-40d7-9ef2-80ff33347a96.png" width="480">

7. "03 Setup The Access Token" でメモした `accessToken` を入力し "Connect The Workspace" を選択します

<img src="https://user-images.githubusercontent.com/1063435/215296993-3e407498-9202-435e-bd9c-e385ae4a5152.png" width="480">

8. "View Your Workspace" を選択したら一度ターミナルに戻ります
9. `NOTION_API_SECRET` が正しくセットされていることを確認します

```sh
echo $NOTION_API_SECRET
```

設定されていなければ下記のように設定します。

```sh
export NOTION_API_SECRET=<YOUR_NOTION_API_SECRET>
```

10. `DATABASE_ID` が Cloudflare Pages のビルド環境と同じであることを確認します

```sh
echo $DATABASE_ID
```

異なる場合は同じ値を設定します。

```sh
export DATABASE_ID=<YOUR_DATABASE_ID>
```

11. メモした `accessToken` を環境変数 `NX_CLOUD_ACCESS_TOKEN` に設定し、コマンドを実行してキャッシュを生成します
    * 記事数約300で20~30分程度時間がかかります

`NX_CLOUD_ACCESS_TOKEN` を環境変数にセットし、正しくセットされていることを確認します。

```sh
export NX_CLOUD_ACCESS_TOKEN=<メモしたaccessToken>
echo $NX_CLOUD_ACCESS_TOKEN
```

キャッシュを生成します。

```sh
yarn cache:fetch
```

12. 再度コマンドを実行しキャッシュが生成されているか確認します(正常にキャッシュが生成されていると今回は実行が速くなります)
    * キャッシュは Notion Page の `last_edited_time` を見て以降は自動で更新されるため、この操作は再度行う必要はありません

```sh
yarn cache:fetch
```

13. ブラウザで Nx Cloud の Workspace を開きキャッシュの結果が "Local Cache Hit" になっていることを確認します

<img src="https://user-images.githubusercontent.com/1063435/215297425-be6ce7cd-15be-46db-b7b0-278acde15970.png" width="480">

<img src="https://user-images.githubusercontent.com/1063435/215297426-c6292008-3268-4eac-8073-9484fbf0cae0.png" width="480">

14. 下記コマンドを実行してローカルでビルドし、かかった時間を報告してください（ローカルビルド）

```sh
yarn build:cached
```

15. [Cloudflare Pages](https://pages.cloudflare.com/) のダッシュボードから環境変数を開きメモしたアクセストークンを `NX_CLOUD_ACCESS_TOKEN` として Production と Preview の両方に追加します

<img src="https://user-images.githubusercontent.com/1063435/216225421-a880846d-3683-478d-ad29-9e678a525d41.png" width="480">

16. ビルド設定を開きます

<img src="https://user-images.githubusercontent.com/1063435/215303878-d674cf07-86cf-4df7-8ea7-ecd3c693de7d.png" width="480">

17. "Build command" を下記に変更して保存します

```bash
npm run build:cached
```

<img src="https://user-images.githubusercontent.com/1063435/215303883-819ba65b-1dfd-4213-b4be-0e796af8d352.png" width="480">

18. ブランチを GitHub に push してデプロイし、Nx Cloud でキャッシュの結果が "Remote Cache Hit" になっていることを確認します
    * ビルドにかかった時間をご報告ください（リモートビルド）

<img src="https://user-images.githubusercontent.com/1063435/215297683-450ef3e5-2938-4a37-9e4b-e9ae04d75a11.png" width="480">

19. 検証が終了したらステップ17で設定したビルドコマンドをデフォルトの `npm run build` に戻し、ローカルで書きコマンドを実行してキャッシュを削除します

```sh
yarn cache:purge
```

**Comment by midnight480** [comment]
12. でエラーになりました。
NxCloud上ではAPI Token自体は読み込めているのですが、
ローカルでそのAPI Tokenを使おうとすると認証が通っていない... ?

```
% yarn cache:fetch           
yarn run v1.22.19
$ node scripts/blog-contents-cache.cjs
@notionhq/client warn: request fail { code: 'unauthorized', message: 'API token is invalid.' }
/Users/tetsuya/Documents/astro-notion-blog/node_modules/@notionhq/client/build/src/errors.js:162
        return new APIResponseError({
               ^

APIResponseError: API token is invalid.
    at buildRequestError (/Users/tetsuya/Documents/astro-notion-blog/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/Users/tetsuya/Documents/astro-notion-blog/node_modules/@notionhq/client/build/src/Client.js:347:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getAllPages (/Users/tetsuya/Documents/astro-notion-blog/scripts/blog-contents-cache.cjs:31:17)
    at async /Users/tetsuya/Documents/astro-notion-blog/scripts/blog-contents-cache.cjs:55:17 {
  code: 'unauthorized',
  status: 401,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [ 'Mon, 30 Jan 2023 13:40:34 GMT' ],
      'content-type': [ 'application/json; charset=utf-8' ],
      'content-length': [ '87' ],
      connection: [ 'close' ],
      'set-cookie': [
        'notion_browser_id=29168cba-9089-4767-9980-3883cabf99d8; Domain=www.notion.so; Path=/; Expires=Tue, 30 Jan 2024 13:40:34 GMT; Secure',
        'notion_check_cookie_consent=false; Domain=www.notion.so; Path=/; Expires=Tue, 31 Jan 2023 13:40:34 GMT; Secure',
        '__cf_bm=tzUGXX9v.kgjyqA5uvmX6xV7G3fH4iTfxrbl9Wbc_Ms-1675086034-0-AS7kaquvTfcFcWJV4p4TFECNHkjA5oIHztVTHujfryc1ViKRp+SYxQm+NRzA+JvBBMNqrO40T5XydC9CpCJRFe8=; path=/; expires=Mon, 30-Jan-23 14:10:34 GMT; domain=.notion.com; HttpOnly; Secure; SameSite=None'
      ],
      'content-security-policy': [
        "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://gist.github.com https://apis.google.com https://www.google.com https://www.gstatic.com https://cdn.amplitude.com https://api.amplitude.com http://dev-embed.notion.co https://widget.intercom.io https://js.intercomcdn.com https://static.zdassets.com https://api.smooch.io\t https://logs-01.loggly.com https://http-inputs-notion.splunkcloud.com https://cdn.segment.com https://analytics.pgncs.notion.so https://o324374.ingest.sentry.io https://checkout.stripe.com https://js.stripe.com https://embed.typeform.com https://admin.typeform.com https://public.profitwell.com https://static.profitwell.com js.sentry-cdn.com https://js.chilipiper.com https://platform.twitter.com https://cdn.syndication.twimg.com https://accounts.google.com https://www.googletagmanager.com https://www.googleadservices.com https://googleads.g.doubleclick.net https://api-v2.mutinyhq.io https://client-registry.mutinycdn.com https://client.mutinycdn.com https://user-data.mutinycdn.com https://cdn.metadata.io https://platformapi.metadata.io https://d2hrivdxn8ekm8.cloudfront.net https://d1lu3pmaz2ilpx.cloudfront.net https://dvqigh9b7wa32.cloudfront.net https://d330aiyvva2oww.cloudfront.net https://cdn.transcend.io https://cdn01.boxcdn.net https://cdn.sprig.com;connect-src 'self' data: blob: https://msgstore.www.notion.so wss://msgstore.www.notion.so ws://localhost:* ws://127.0.0.1:* https://notion-emojis.s3-us-west-2.amazonaws.com https://s3-us-west-2.amazonaws.com https://s3.us-west-2.amazonaws.com https://notion-production-snapshots-2.s3.us-west-2.amazonaws.com https://cdn.amplitude.com https://api.amplitude.com https://www.notion.so https://api.embed.ly http://dev-embed.notion.co https://js.intercomcdn.com https://api-iam.intercom.io https://uploads.intercomcdn.com wss://nexus-websocket-a.intercom.io https://ekr.zdassets.com https://ekr.zendesk.com\t https://makenotion.zendesk.com\t https://api.smooch.io\t wss://api.smooch.io\t https://logs-01.loggly.com https://http-inputs-notion.splunkcloud.com https://cdn.segment.com https://api.segment.io https://analytics.pgncs.notion.so https://api.pgncs.notion.so https://o324374.ingest.sentry.io https://checkout.stripe.com https://js.stripe.com https://cdn.contentful.com https://preview.contentful.com https://images.ctfassets.net https://www2.profitwell.com https://tracking.chilipiper.com https://api.chilipiper.com https://api.unsplash.com https://boards-api.greenhouse.io https://accounts.google.com https://oauth2.googleapis.com https://www.googletagmanager.com https://analytics.google.com https://www.googleadservices.com https://googleads.g.doubleclick.net https://region1.google-analytics.com https://region1.analytics.google.com https://www.google-analytics.com https://api-v2.mutinyhq.io https://client-registry.mutinycdn.com https://client.mutinycdn.com https://user-data.mutinycdn.com https://cdn.metadata.io https://platformapi.metadata.io https://d2hrivdxn8ekm8.cloudfront.net https://d1lu3pmaz2ilpx.cloudfront.net https://dvqigh9b7wa32.cloudfront.net https://d330aiyvva2oww.cloudfront.net https://cdn.transcend.io https://telemetry.transcend.io https://api.statuspage.io https://pgncd.notion.so https://api.statsig.com https://statsigapi.net https://exp.notion.so https://file.notion.so notion://file.notion.so https://api.box.com https://*.mux.com https://api.sprig.com https://storage.googleapis.com https://cdn.sprig.com https://cdn.userleap.com;font-src 'self' data: https://cdnjs.cloudflare.com https://js.intercomcdn.com https://cdn01.boxcdn.net;img-src 'self' data: blob: https: https://platform.twitter.com https://syndication.twitter.com https://pbs.twimg.com https://ton.twimg.com https://region1.google-analytics.com https://region1.analytics.google.com https://*.mux.com;style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://github.githubassets.com https://js.chilipiper.com https://platform.twitter.com https://ton.twimg.com https://accounts.google.com https://cdn.transcend.io https://cdn01.boxcdn.net;media-src blob: https: http: https://file.notion.so notion://file.notion.so https://*.mux.com;worker-src blob:;frame-src https: http: https://accounts.google.com"
      ],
      'x-dns-prefetch-control': [ 'off' ],
      'x-frame-options': [ 'SAMEORIGIN' ],
      'strict-transport-security': [ 'max-age=5184000; includeSubDomains' ],
      'x-download-options': [ 'noopen' ],
      'x-content-type-options': [ 'nosniff' ],
      'x-permitted-cross-domain-policies': [ 'none' ],
      'referrer-policy': [ 'strict-origin-when-cross-origin' ],
      'x-xss-protection': [ '0' ],
      etag: [ 'W/"57-QCRLT3IovYEW+CkwyJQlFtiXiG8"' ],
      vary: [ 'Accept-Encoding' ],
      'cf-cache-status': [ 'DYNAMIC' ],
      server: [ 'cloudflare' ],
      'cf-ray': [ '791a9ebdca968d18-KIX' ]
    }
  },
  body: '{"object":"error","status":401,"code":"unauthorized","message":"API token is invalid."}'
}

Node.js v18.10.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by otoyo** [comment]
@midnight480 検証ありがとうございます！
環境変数 `CACHE_CONCURRENCY` のエラーを調べようとしたところ、Notion DB側で列を編集すると全てのページの最終更新日が更新されてキャッシュが切れてしまうことがわかったので、危ないので機能からは外そうと思います（キャッシュがないとNotion APIにリクエストするため）。

その他コメントいただいた点を手順に反映しました！

**Comment by otoyo** [comment]
memo:
ハッシュ値が変わってしまうケースがあるので調査する。
![スクリーンショット 2023-01-31 9 26 43](https://user-images.githubusercontent.com/1063435/215627308-edf1b2ba-fcc2-4255-a58f-c22943e31a4c.png)

**Comment by otoyo** [comment]
👆対応済み

**Comment by otoyo** [comment]
検証ありがとうございます。

> Nx Cloud でキャッシュの結果が "Remote Cache Hit" になっていること確認しましたがローカルでのみ上手く動作していましたがリモートは動作していないようでした。

これはローカルで `cache:fetch` を実行した際に "Remote Cache Hit" になっていたということでしょうか？
ローカルで `cache:fetch` を実行した後に再度 `cache:fetch` を行ったり `build:cached` を行った場合には "Local Cache Hit" になるかと思います。
リモートで動作していないというのは何を根拠に判断されたのでしょうか？

> ちなみにVercelでデプロイすると平均で４−５分でのデプロイになります。(キャッシュロジック無しで)

それだけ速ければVercelで運用する場合はキャッシュは不要そうですね。

**Comment by nuovotaka** [comment]
ローカルで `cache:fetch` を実行した際は 'Local Cache Hit' になりました。
githubにプッシュしデプロイした後 Nx Cloud を確認したところ"Remote Cache Hit"になっていませんでした。
> リモートで動作していないというのは何を根拠に判断されたのでしょうか？
Nx Cloud の Workspace を開きキャッシュの結果を確認したところ
<img width="957" alt="スクリーンショット 2023-02-01 20 52 00" src="https://user-images.githubusercontent.com/11598404/216035219-6e3769ab-e060-4e0d-b255-c84ef01813bf.png">

**Comment by otoyo** [comment]
> githubにプッシュしデプロイした後 Nx Cloud を確認したところ"Remote Cache Hit"になっていませんでした。

念のため確認ですが、デプロイ後最新のRunで確認されてますか？

![image](https://user-images.githubusercontent.com/1063435/216036326-d1874a91-6b13-4443-ac51-16e7e10d4752.png)

**Comment by nuovotaka** [comment]
リロードして最新のものを利用しましたが、ローカルで行った結果ですね。
今も、githubにプッシュしたブランチを削除してCloudflareで試しましたがNx Cloudの結果がローカルで行った結果以降変わっていません。３時間前のままですね。

**Comment by nuovotaka** [comment]
ちなみにCloudflareでの結果は。。。
<img width="681" alt="スクリーンショット 2023-02-01 20 58 39" src="https://user-images.githubusercontent.com/11598404/216038131-55abb77d-1a18-44bf-9ccd-501ae9aea00e.png">

**Comment by otoyo** [comment]
> 今も、githubにプッシュしたブランチを削除してCloudflareで試しましたがNx Cloudの結果がローカルで行った結果以降変わっていません。３時間前のままですね。

これはおそらく環境変数`NX_CLOUD_ACCESS_TOKEN` が正しく設定されていなさそうです。ご確認いただけますか？

**Comment by nuovotaka** [comment]
`NX_CLOUD_ACCESS_TOKEN`  トークンの設定していなかったです。
今、CloudflareおよびVercelそれぞれでやり直しを行っているところです。少々お待ちください。

**Comment by nuovotaka** [comment]
アクセストークンを設定して再度やり直した結果です。

- Vercel デプロイ時間
<img width="719" alt="スクリーンショット 2023-02-01 21 54 19" src="https://user-images.githubusercontent.com/11598404/216050194-5bddbaac-5873-4c7f-9d8b-c198b1ec6a36.png">

- Cloudflare デプロイ時間
<img width="689" alt="スクリーンショット 2023-02-01 21 59 45" src="https://user-images.githubusercontent.com/11598404/216050308-1225b11e-a68a-4f7a-bfc9-e4dd7b4b34c5.png">

**Comment by nuovotaka** [comment]
1. ビルドの成否　＞　成功
2. エラーの場合はエラーメッセージの内容　＞　エラーはなし
3. デバッグに協力いただけるか否か　＞　時間が合えば協力します。
4. ビルドしたブログの記事数とビルドにかかった時間　＞　記事数 : 236
5. 手順でわかりにくかったところ　＞　Vercel, Cloudflare それぞれで環境変数(Nx Cloudのアクセストークン設定の抜け落ち)

以上

**Comment by otoyo** [comment]
@nuovotaka ご確認ありがとうございます。
やはりVercelのビルドめちゃくちゃ速いですね。見た感じ独自にビルドをキャッシュしてるみたいですね。

> 手順でわかりにくかったところ　＞　Vercel, Cloudflare それぞれで環境変数(Nx Cloudのアクセストークン設定の抜け落ち)

ここはごもっともですので手順に追加しました。

**Comment by otoyo** [comment]
みなさまご協力ありがとうございました！
