### ISSUE TITLE
ローカル実行時 /blog にアクセスすると"Cannot read properties of undefined (reading files)"エラー

### ISSUE THREAD

**Issue by otoyo** [otoyo/astro-notion-blog#3]
![FnDIRyGaAAAu_iM](https://user-images.githubusercontent.com/1063435/213900415-61eb0d0b-5663-47cf-82d0-35c325ec4185.jpeg)

[ぐだぐだマン](https://twitter.com/gdgd_devs) さんから報告いたただいたもの。
* https://twitter.com/gdgd_devs/status/1617012662394851329?s=20&t=CFoaIFoY73Zm2SVvUk1rLw

再現性は現時点では取れておらず。
おそらく画像が https://github.com/otoyo/astro-notion-blog/issues/2 で取れておらず発生しているかもしれない。

**Comment by herohoro** [comment]
私は/blogは問題なかったですが、
記事を開くとエラーになっています。

<img width="961" alt="スクリーンショット 2023-01-22 13 35 20" src="https://user-images.githubusercontent.com/24947347/213900829-4259ceba-1353-4584-8a92-67c5f9234ed3.png">

**Comment by otoyo** [comment]
おそらく #2 と同じ原因だと思われます。
https://github.com/otoyo/astro-notion-blog/pull/5 の修正を取り込んで試していただけますでしょうか。

**Comment by otoyo** [comment]
解決済み
