### ISSUE TITLE
Feature Requests for ver 0.3 / バージョン0.3の機能要望

### ISSUE THREAD

**Issue by otoyo** [otoyo/astro-notion-blog#31]
The features being planed so far are as follows:
現在計画している機能は下記です。

* OG image for each posts / 個別記事用のOG画像

Leave a comment if you have requests.
もし要望があればコメントしてください。

**Comment by gdgdDevs** [comment]
要望というかアイデアなのですが、Notionのページで設定したアイコンとカバー画像を利用できるとうれしいです！

![notion](https://user-images.githubusercontent.com/123616327/216621795-01cb087d-99b0-42a6-98a2-6da701128527.jpg)

**Comment by otoyo** [comment]
確かにそれは良いアイデアですね！
アイコンの方は割と簡単にできそうなので、個別記事の方でタイトル横に付けるなど検討してみます！
カバー画像の方はどんな風に表示されると良いでしょうか？
今すぐアイデアがなければひとまずデータだけ取得しておいて使い方はユーザーに任せるでもいいのかな〜とも思っております。

**Comment by gdgdDevs** [comment]
ご検討ありがとうございます！
見出しの横にアイコンがあると可愛い感じでいいかなと思いました。

カバー画像はOGの代わりに、とも思ったのですがotoyoさんが言うようにユーザーがどこかで使えるようにしていただくだけでも幅が広がってよさそうな気がします。

**Comment by zimazine** [comment]
連続ですが、せっかくなのでアイデアだけ出させてください。
easyのときからこれがあったらもっと使いやすいなと思っていた機能です。

- 画像タッチでモーダル
カラム表示など画像が小さくて見にくいことがあるので拡大機能がほしい。

- コードブロックのコードをコピー
技術ブログのようななものにも使いやすいかなと思います。

**Comment by otoyo** [comment]
モーダルでの画像拡大とコードブロックのコピーがあると良さそうですね！
特にコピーの方は割と簡単にできそうなので実装を検討してみます！

**Comment by zimazine** [comment]
ありがとうございます！この機能があったらとてもうれしいです。
あとは記事の一番上に戻るボタンのようなものがあるとスマホで使いやすそうな気がしました。

**Comment by otoyo** [comment]
確かに上に戻るボタンもあると良さそうですね。アイデアありがとうございます！

**Comment by otoyo** [comment]
アイデアありがとうございました。ここまでいただいたアイデアは全て0.3で実装予定です。
進捗は下記をご覧ください。
https://github.com/otoyo/astro-notion-blog/pull/45
