### ISSUE TITLE
困った方を助ける解説記事を共有しあう活動に素敵な名前を考えたい

### ISSUE THREAD

**Issue by herohoro** [otoyo/astro-notion-blog#35]
# 経緯
[追加してほしいドキュメント](https://github.com/otoyo/astro-notion-blog/issues/32)が設置されました。  

# 提案
仕組みとしてはボランティアであることを前提に  
私たちコミュニティメンバーがwin-winな関係性を作り出せる活動として  
認識してもらえるような表現を考えたい

## 実際解説記事を書いて得られたこと

- 記事の構成を考える練習になった
- 実際に困っている人に向けて書ける機会があって何を書くべきかの吟味ができた
- 読んでもらえることでブログを継続するモチベーションにもなった
- 「ありがとう」の声を聞けてまた記事を書きたくなった

## 例えばこんなフレーズ？

- 解説記事を書くトレーニング
- あなたのために書くラブレター
- 遊び方取り扱いナレッジ

コミュニティメンバーそれぞれが目的をもってブログを開設されているかと思います。
目的が異なるのに「改造」「記事」を通して交流が生まれるのって不思議ですよね。。。
ボランティア精神は無いんだけど、  
書きたくなる解説記事。  
不思議でたまらなくなり、これをうまく言語化できないものかとIssueを立たせていただきました。

**Comment by otoyo** [comment]
特に動きがないようですのでクローズします。何かありましたら再オープンしてください。
