### ISSUE TITLE
ローカルでyarn devしてブログ一覧を開くとInvalid request URLエラー

### ISSUE THREAD

**Issue by otoyo** [otoyo/astro-notion-blog#71]
![image](https://user-images.githubusercontent.com/1063435/221338526-a2864c18-0004-4dac-b964-c3c0738ade3d.png)

* https://twitter.com/gdgd_devs/status/1629323835706318850?s=20
* https://twitter.com/snk_skr/status/1629049490152820739?s=20

OSはmacOS, Windows共に発生。
再現性はなし→再現した

**Comment by otoyo** [comment]
# デバッグ
node_modules/@notionhq/client/build/src/Client.js
L339
```diff
  try {
+     console.log(url.toString())
      const response = ...
```

**Comment by okash1n** [comment]
先程初めて使わせていただきました。 `.evn` には `NOTION_API_SECRET` および `DATABASE_ID` を記載しましたが、Invarid request URL になります。

なお、Cloudflare側では問題なく表示されました。

環境はWin11、WSLです。

**Comment by otoyo** [comment]
@okash1n 情報ありがとうございます。引き続き調査進めます。

**Comment by otoyo** [comment]
![image](https://user-images.githubusercontent.com/1063435/221339884-d991c3e7-2eef-44c0-b4f9-50600cce9388.png)

DATABASE_IDが入るところに `database/` という文字列が入っていることがわかった。

**Comment by otoyo** [comment]
`.env` を使用したところ再現した。

**Comment by otoyo** [comment]
https://github.com/otoyo/astro-notion-blog/pull/72 で修正

**Comment by otoyo** [comment]
https://github.com/otoyo/astro-notion-blog/pull/72 で修正したので同じ症状の方取り込んで試していただけますと幸いです。

**Comment by otoyo** [comment]
# 原因

0.3.0でNOTION_API_SECRETなどの環境変数の読み込みを `process.env` 経由に変更したが、`.env` に書かれた環境変数は `import.meta.env` 経由でしか読み込めなかった。
https://docs.astro.build/ja/guides/environment-variables/

自身は `.env` を使っていなかったため最初再現しなかった。

**Comment by okash1n** [comment]
取り込んで問題なく表示されました！

**Comment by otoyo** [comment]
ご報告ありがとうございます！よかったです！
