### ISSUE TITLE
Notion Iconに対応したい

### ISSUE THREAD

**Issue by trickstar13** [otoyo/astro-notion-blog#78]
現在、NotionのページやCalloutブロックにて、絵文字のほかに「アイコン」を選べるようになっています。
<img width="417" alt="notion-icons" src="https://user-images.githubusercontent.com/4230465/221399591-9848891c-b443-4c68-b351-878ff5774a89.png">

いまはこれらのアイコンを選んでも、astro-notion-blog側で未対応のため、ブログ上ではアイコンが表示されません。
アイコンを表示できるように変更したいです。

---

Notionのドキュメント上ではこのアイコンについての記載を見つけられなかったのですが、レスポンスを見ると、`icon.external.url` などとして、このアイコンのSVG画像ファイルのURLを取得できるようです。

ページのNotionアイコン
<img width="534" alt="page-icon" src="https://user-images.githubusercontent.com/4230465/221399645-89061543-01b4-429d-8323-8bf86e8c1580.png">

CalloutブロックのNotionアイコン
<img width="533" alt="callout-icon" src="https://user-images.githubusercontent.com/4230465/221399656-af92df76-efa6-43f8-b797-18e06c859c65.png">
※ externalの中身は `{ url: 'https://www.notion.so/icons/book_brown.svg' }` の形式でした

アイコン画像の有効期限はなさそうに見えますので、単純にこのURLをそのまま画像として表示すればいいのかなと思っています。

---

余談
「カスタム」からアイコンをアップロードした場合は、期限つきの画像URLが返ってくるようなので、こちらに対応する場合はダウンロードが必要になりそうです…！また別でイシュー等たてるほうが良さそうですね。
<img width="1002" alt="custom-icon" src="https://user-images.githubusercontent.com/4230465/221399912-da4fef33-e2cb-4136-b301-532fe6f757c4.png">

**Comment by otoyo** [comment]
アイデアありがとうございます！
カスタムから選んだ場合のアイコンのURLは期限は無さそうですね。`img` タグでそのまま参照してあげる形で簡単に実現できそうですね。

**Comment by otoyo** [comment]
TODO: 共用体型が必要なので interface を type で定義し直す。

**Comment by otoyo** [comment]
https://github.com/otoyo/astro-notion-blog/pull/90 で実装しました。

**Comment by trickstar13** [comment]
ありがとうございます！🙏
早速使わせてもらっています、とてもかわいいです🥰
