### ISSUE TITLE
サブディレクトリが存在する環境で fslightbox.js のパスが合わない

### ISSUE THREAD

**Issue by hkob** [otoyo/astro-notion-blog#83]
## 不具合の概要

サブディレクトリ環境で fslightbox.js が読み込めない

## 再現方法

BASE_DIR を設定して環境で yarn build する

## エラーログ

fslightbox.js が読み込めないというエラーになります。

## 期待する挙動

subdir/scripts/fslightbox.js という正しいパスになって欲しいです。

## リポジトリとブランチ名

main

## 追加情報

現在、fslightbox.js が絶対パスになってしまっています。
```
    {ENABLE_LIGHTBOX && <script src="/scripts/fslightbox.js" />}
```

ここも getNavLink で BASE_DIR に基づくパスが出せればいいと思います。
```
    {ENABLE_LIGHTBOX && <script src={getNavLink('/scripts/fslightbox.js')} />}
```

**Comment by otoyo** [comment]
ご報告ありがとうございます。
https://github.com/otoyo/astro-notion-blog/pull/86 で修正しました。

**Comment by hkob** [comment]
ありがとうございました。
